### ISSUE TITLE
EDITOR_AUTO_INDENT does not work

### ISSUE THREAD

**Issue by Rentheus** [SilenZcience/cat_win#1]
The flag EDITOR_AUTO_INDENT does not toggle auto indent

**To Reproduce**
Set EDITOR_AUTO_INDENT to false in config file

**Expected behavior**
The editor should **not** indent

**Desktop (please complete the following information):**
 - OS: Win10
- Version: latest as of now

**Comment by SilenZcience** [comment]
Thanks for letting me know.
This Issue has been resolved (commit: d56570dd01ab400f90c62030cff58fa1fbd9e52f) and will be fixed in the next Release ([Changelog](https://github.com/SilenZcience/cat_win/blob/dev/CHANGELOG.md#bugfixes)).
